AWSTemplateFormatVersion: 2010-09-09


Description: |
  Create static website for kittens carousel 


# Parameters:
  
Resources:

  rSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP" # Required
      GroupName: "KittensSecGroup"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  

  rWebserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-066784287e358dad1
      InstanceType: t2.micro
      KeyName: ec2-ssh-key-braxton
      SecurityGroupIds: 
        - !GetAtt rSecurityGroup.Id
      SecurityGroups: 
        - "String"
      Tags: 
        - Key: "String"
          Value: "String" 
      UserData: "String"
     
# Outputs:
